### ISSUE TITLE
Streamline pointer events

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#126]
From David in https://github.com/USGS-VIZLAB/water-use-15/issues/97#issuecomment-378413238:

Looks like we reload a category whenever the button is hovered over, even if that category is already loaded. Same with the mouseout. There should be a check there to see if the category is already loaded.

And there seems to be mouse-in/mouse-out happening when you click on a category, not sure that should be happening. I would think it is less snappy since it is loading the new circles twice.

Might we also want to add a very small delay to deciding to load a new category, so just incidentally dragging the cursor over the buttons doesn't trigger category changes? Although if the category changes get snappier this might not be an issue.

Lindsay says:

that's a good idea....Here's an example for click vs double click and I think that's pretty much what we would use for mouseover vs click. We should also handle mouseout differently if it's been clicked. No need to revert the category.

https://github.com/almende/vis/issues/203#issuecomment-48481501

**Comment by wdwatkins** [comment]
To further clarify, I would suggest handling the mouse in/out behavior before adding any delay with the category change.  IMO the delay is only needed if there is still a substantial performance penalty for switching categories.

**Comment by lindsaycarr** [comment]
Well, I think we need some type of delay regardless so that moving your cursor just over the top accidentally doesn't initiate a switch. It should definitely be lower priority than the other changes, and should be a pretty small delay, like 100 ms or something.

So things to fix:

1. Don't switch categories if moused or clicked on the same one (handle [here](https://github.com/USGS-VIZLAB/water-use-15/blob/master/js/build_map.js#L140-L146)).
2. Don't revert categories if mousing out of the same one that is already active (handle [here](https://github.com/USGS-VIZLAB/water-use-15/blob/master/js/build_map.js#L148-L150)).
3. Add small delay to mouseover events so that accidental hovers don't trigger a category switch (handle [here](https://github.com/USGS-VIZLAB/water-use-15/blob/master/js/build_map.js#L145-L147)).

**Comment by aappling-usgs** [comment]
Tasks 1 and 2 are done. I'm OK punting on task 3, which may or may not be important as we improve the load time.
