### ISSUE TITLE
Improve text layout

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#198]
Jordan, 4/11: layout needs some work and perhaps some separation between the different concepts. Current view has things kind of floating out there (pie, pie map, placeholder rank-'em states)

Lindsay, 4/18: Reduce header font size and text font size for “how to use the figure” (make it more like a caption). Then wrap text around static pie chart if it looks good

**Comment by lindsaycarr** [comment]
Part of fixing the text up (#203) required me to think about moving things into captions and such. In doing this I tried to add some basic caption-like style and functionality, but that can be totally redone. The point is that you know it's not part of the main body text in order to adjust the layout here :) My PR with my text changes is not yet up, but just wanted to post these thoughts before I forgot.
