### ISSUE TITLE
is national pie map using old data? 

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#330]
I noticed that `piemap` and `thumbnails` use cache/county_centroids_wu.json, which I think is an older version of the file but doesn't exist anymore if you have cleared your cache recently. 
I think we now have two files that need to be combined to contain that info: county_centroids_USA.json and county_centroids_wu.tsv	

This may not be an issue _unless_ this _wu.json file predates the xls update of the county data, in which case it would differ from the newer file(s) in some ways.

**Comment by lindsaycarr** [comment]
Working on updating now because switch from `county_centroids_wu.json` to `county_centroids_wu.tsv` (https://github.com/USGS-VIZLAB/water-use-15/commit/ff323878db301a0b389b9626bcee9fdbc4eb3325) predates switch to new data (https://github.com/USGS-VIZLAB/water-use-15/pull/221/files), so that cached file is outdated.
