### ISSUE TITLE
Highlight dot doesn’t change w categories

### ISSUE THREAD

**Issue by jread-usgs** [USGS-VIZLAB/water-use-15#364]
![71a594a8-4133-47b0-9253-21af26e60424](https://user-images.githubusercontent.com/2349007/40873773-4aec17b2-662c-11e8-8cf6-fe328b939aab.png)

I assume this is an issue with mobile only. The dot for the original clicked category doesn’t update, and therefore isn’t colored or sized appropriately for the new category. Using iPhone

**Comment by lindsaycarr** [comment]
Just tested on Samsung Galaxy - the county is highlighting and staying highlighted, but the actual values shown in the legend aren't changing. Hmmm. Looking into it now

**Comment by lindsaycarr** [comment]
Haven't confirmed and not sure when exactly this bug was introduced, but I have a feeling it was something in here maybe? https://github.com/USGS-VIZLAB/water-use-15/pull/356/commits/1ad1828b423bccc4f20d6818fcbf4020f3c40028

However it was introduced, I think it's because when `updateCircleCategory` is called, the highlighted one isn't getting included. https://github.com/USGS-VIZLAB/water-use-15/blob/master/js/circles.js#L114

**Comment by lindsaycarr** [comment]
this is an issue on master as of 255c9f5073d9d44c1081f64952839e56507b33e8

**Comment by lindsaycarr** [comment]
Alright - this was difficult to track because of the mobile vs not BUT I think I've got it. 

1. When you click a new county on mobile, the category correctly updates. The category not changing for the highlighted county is only an issue when you don't change counties and update the category. This is because the county .on("click") code calls updateLegendText, highlightCounty, highlightCircle, etc BUT that code is not called when you are on a county and just switch categories. So really, something in `updateCategory` should be handling this.

2. This works on desktop because you aren't able to hover over a county at the same time as switching the category.

**Comment by lindsaycarr** [comment]
Checked on my phone and it's working now.
