### ISSUE TITLE
Show adjacent states when zoomed in (S)

### ISSUE THREAD

**Issue by aappling-usgs** [USGS-VIZLAB/water-use-15#95]
Just show state boundaries/background, not counties, for non-focal states.

Design decision: How should focal vs non-focal states be indicated - by position, by varying shades of grey in background, by the presence/absence of county boundaries, etc.?

**Comment by jread-usgs** [comment]
For starters, the adjacent states wouldn’t display counties and fill would be a different (lesser emphasis) shade. Might want to consider also using a different border style even if simple as thicker stroke compared to neighbors.

**Comment by lindsaycarr** [comment]
PR coming soon for this!

Moved counties under states boundaries to get rid of this:
![image](https://user-images.githubusercontent.com/13220910/38276705-847600c4-375b-11e8-963d-18d5fa011750.png)

Tried to get county lines to transition to turn on, but couldn't get them to work unless I commented out the transition part (link to commit: ). Also, had to make highlighting a county on hover be in js if emphasizing a fill for the zoomed in state was also in js (otherwise emphasized fill color trumped my css class and you couldn't see what you hovered over). So, in the end, reverted back to all of those style changes being class switches (so no transitioning). The added benefit of this method is that it's actually much faster when you're hovering on and off of counties than if we switched their fill via js. 

Tried dotting adjacent state lines rather than just filling focal state. Worked with TX because it's one of the last paths, but didn't work with AL because adjacent states are painted on after:

![image](https://user-images.githubusercontent.com/13220910/38326939-a84fe06c-380c-11e8-9037-b8a07dcce6e9.png)

![image](https://user-images.githubusercontent.com/13220910/38326997-c53f4b04-380c-11e8-8557-88d9aabbc6b6.png)

**Comment by aappling-usgs** [comment]
What if the focal state gets a thicker black border than the dashed lines, such that it doesn't matter which is on top of which?

**Comment by lindsaycarr** [comment]
Yeah, that's what was happening. Although, I don't think I was scaling the non-focal state borders like the focal state was...which would explain why TX is fine. I'll try that

**Comment by aappling-usgs** [comment]
I think this is done. Lindsay spent 5 hours.
